force-app/main/default/objects/AppConfig__c/AppConfig__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>AppConfig</label>
</CustomObject>

force-app/main/default/objects/AppConfig__c/fields/diagnosisEnabled__c.field-meta.xml
<CustomField>
    <fullName>diagnosisEnabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>diagnosisEnabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SettingWrapperTest.cls
@Istest
public with sharing class SettingWrapperTest {
  @IsTest
  public static void TestSetting(){
    AppConfig__c configTest = new AppConfig__c();
    configTest.diagnosisEnabled__c = false;

    SettingWrapper.testConfig = configTest;

    Test.startTest();
    //.,a,.
    Test.stopTest();

    System.assertEquals(false, SettingWrapper.diagnosisEnabled,
    'diagnosis setting should be false');
  }
}