force-app/main/default/objects/AppConfig__c/AppConfig__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>AppConfig</label>
</CustomObject>

force-app/main/default/objects/AppConfig__c/fields/diagnosisEnabled__c.field-meta.xml
<CustomField>
    <fullName>diagnosisEnabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>diagnosisEnabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SettingWrapper.cls
public without sharing class SettingWrapper {
  @TestVisible
  private static AppConfig__c testConfig = null;

  public static Boolean diagnosisEnabled {
    get {
      return getConfig().diagnosisEnabled__c;
    }
  }

  private static AppConfig__c getConfig() {
    if (Test.isRunningTest()) {
      if (testConfig != null) {
        return testConfig;
      }
      testConfig = createDefaultConfig();
      return testConfig;
    }

    Appconfig__c setting = AppConfig__c.getInstance('default');
    if (setting == null) {
      setting = createDefaultConfig();
      Database.insert(setting);
    }
    return setting;
  }

  private static AppConfig__c createDefaultConfig() {
    Appconfig__c setting = new Appconfig__c();
    setting.name = 'default';
    setting.diagnosisEnabled__c = true;
    return setting;
  }
}